"""
Metaprogramming factory for creating initialization step services.

This factory uses type() to dynamically generate service classes that follow
a consistent pattern: accept inputs, call a builder function, return a typed output.

Inspired by OpenHCS's LazyDataclassFactory and enum_factory patterns.
"""

from typing import Callable, TypeVar, Type, Any


T = TypeVar('T')


class InitializationStepFactory:
    """
    Factory for creating metaprogrammed initialization step services.
    
    Each service follows the pattern:
        class SomeService:
            @staticmethod
            def build(*args, **kwargs) -> OutputType:
                return builder_func(*args, **kwargs)
    
    This eliminates boilerplate for simple builder services that just
    wrap a function call with a typed interface.
    """
    
    @staticmethod
    def create_step(
        name: str,
        output_type: Type[T],
        builder_func: Callable[..., T]
    ) -> Type:
        """
        Create a service class with a .build() method.
        
        Args:
            name: Name of the service class (e.g., "ParameterExtractionService")
            output_type: Return type of the builder function (for documentation)
            builder_func: Function that performs the actual work
            
        Returns:
            Dynamically generated service class with .build() static method
            
        Example:
            >>> def extract_params(obj, exclude):
            ...     return ExtractedParameters(...)
            >>> 
            >>> ParameterExtractionService = InitializationStepFactory.create_step(
            ...     "ParameterExtractionService",
            ...     ExtractedParameters,
            ...     extract_params
            ... )
            >>> 
            >>> result = ParameterExtractionService.build(my_obj, ['func'])
        """
        
        # Create the build method
        def build(*args, **kwargs) -> output_type:
            """Execute the builder function and return typed result."""
            return builder_func(*args, **kwargs)
        
        # Create the class dynamically using type()
        service_class = type(
            name,
            (),  # No base classes
            {
                'build': staticmethod(build),
                '__doc__': f"""
                {name} - Metaprogrammed initialization step.
                
                Returns: {output_type.__name__}
                
                This class was generated by InitializationStepFactory to provide
                a consistent interface for initialization steps.
                """.strip(),
                '_output_type': output_type,
                '_builder_func': builder_func,
            }
        )
        
        return service_class

